service: rebooking-generator
useDotEnv: true

frameworkVersion: '3'

plugins:
  - serverless-step-functions
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs14.x

  stage: ${opt:stage, env:AWS_STAGE, 'dev'}
  region: ${opt:region, env:AWS_REGION, 'eu-central-1'}
  stackName: ${self:service}-${self:provider.stage}

functions:
  rebooking-generator:
    handler: src/rebooking-generator.handler
    environment:
      CANCELLATIONS_TABLE_ID: ${param:CANCELLATIONS_TABLE_ID}
      ROZIE_EVENTS_QUEUE_URL: ${param:ROZIE_EVENTS_QUEUE_URL}
      EVENTS_TABLE_ID: ${param:EVENTS_TABLE_ID}
    logging: true
    events:
      - schedule: cron(2/10 * ? * * *)
    iamRoleStatementsName: rebooking-generator-${self:provider.stage}-iam-role
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:DeleteItem
        Resource: ${param:CANCELLATIONS_TABLE_ARN}
      - Effect: "Allow"
        Action:
          - dynamodb:Query
        Resource: ${param:CANCELLATIONS_TABLE_ARN}/index/byFlightID
      - Effect: "Allow"
        Action:
          - dynamodb:Query
        Resource: ${param:EVENTS_TABLE_ARN}/index/byEventType
      - Effect: "Allow"
        Action:
          - sqs:SendMessage
        Resource: ${param:ROZIE_EVENTS_QUEUE_ARN}
